[package]
name = "membrane"
version = "0.1.0"
authors = ["Membrane Devs"]
edition = "2018"

[dependencies]
osmosis-std = {version = "0.16.1"}
cosmwasm-std = { version = "1.0.0", default-features = false, features = ["cosmwasm_1_1"] }
cosmwasm-schema = "1.1.0"
cw-coins = "0.6.1"
pyth-sdk-cw = "1.0.0"
prost = "0.11"
uint = "0.8"
cw-storage-plus = "0.13.2"
schemars = "0.8.8"
serde = { version = "1.0.137", default-features = false, features = ["derive"] }
serde-json-wasm = { version = "1.0.0" }
thiserror = { version = "1.0.31" }


